language: python
python:
  - "3.5"
  
#install dependencies
install: pip install -r requirements.txt

#tests to run
script: nosetests

notifications:
  slack: 
    secure: "dyzV4RXkGL+MD6Y4U3dsZrozN/Hvtn+RNn7TIpJqEj5mfiD5B5+CroSqJtEI1MIpMDiyFfDYNJ2kGy7SKV+3RxdStZ9oTqtLSVFsQP7NrLig3P6WcBpZbQDf7CEeGO6YjQVQ6b0rAoroBmVYqYwDbgRJ9k/QF5HfjY7Rnq7dkIR442/uKjVLPF5SkKHEdTirfTU5fGY1bpNka2D+5r6wBQc93UPN+ZC0rUBzQGQ7s5+HlZOabMKzoW1Fozjft4cfHpFwiOYpU+KYKD/HqnWBDPq8c1XUs0dPM4Y4DfgLV8Xd6lGFqnXCt1Ho0UDd5AvYcMaSIDoZGqTGtxtaIaqpIGH0VhGwvflKleoP9WXlyYhMKtRIT39n1z7fSb0i38YVSpjXdKt/2ZWjzHEx3Em2SkwQ27AThKCQ7YbFPv9tzxn/NNyfQlYFTLCQJvkmExWmCx3E1hyjOCYfwLCk64Kb+4iHTN4v9/jtPJAOFbLY3nLxj+zcCuH4RmzZatiGs1VdhrUmeDlbfWJBATSbn6kcKJxcCNrdNOeBexfPElsbNeJBpxsT1yaiQU6cNcftV8GK0JbuYNxGwtXjpIVlSuSMHsRhCawLHdMrnzyj6QeI0YAH8evzaTDzKHpeLfwUsKNcrl7zMMt5m3YeAYH9SvzKIG8P64NJemnDOlm3PKetnHM="

